[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"

[secrets]
  SECRETS_SCAN_OMIT_PATHS = ["dist/assets/*.js"]

[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "vite"

[context.branch-deploy]
  command = "vite"

[dev]
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  framework = "#custom"
  autoLaunch = true

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/v1/memes"
  to = "/.netlify/functions/api-v1-memes-post"
  status = 200
  force = true
  methods = ["POST"]

[[redirects]]
  from = "/api/v1/memes"
  to = "/.netlify/functions/api-v1-memes-get"
  status = 200
  force = true
  methods = ["GET"]

[[redirects]]
  from = "/api/v1/memes/:id"
  to = "/.netlify/functions/api-v1-memes-get-by-id/:id"
  status = 200
  force = true
  methods = ["GET"]

[[redirects]]
  from = "/api/v1/memes/search"
  to = "/.netlify/functions/api-v1-memes-search"
  status = 200
  force = true
  methods = ["GET"]

[[redirects]]
  from = "/api/v1/tags"
  to = "/.netlify/functions/api-v1-tags"
  status = 200
  force = true
  methods = ["GET"]

[[redirects]]
  from = "/api/v1/tags/:tag/memes"
  to = "/.netlify/functions/api-v1-tags-memes/:tag"
  status = 200
  force = true
  methods = ["GET"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization, x-api-key"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
