[build]
  command = "npm run test:coverage && npm run codecov && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[secrets]
  SECRETS_SCAN_OMIT_PATHS = ["dist/assets/*.js"]

[context.production]
  command = "npm run test:coverage && npm run codecov && npm run build"

[context.deploy-preview]
  command = "npm run test:coverage && npm run codecov && npm run build"

[context.branch-deploy]
  command = "npm run test:coverage && npm run codecov && npm run build"
