[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"

[secrets]
  SECRETS_SCAN_OMIT_PATHS = ["dist/assets/*.js"]

[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "vite"

[context.branch-deploy]
  command = "vite"

[dev]
  command = "vite"
  targetPort = 5173
  port = 8888
  framework = "#custom"
  autoLaunch = true

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
